wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1678236559.355906
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.12
      5: 0.13.10
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.001
n_channels:
  desc: null
  value: 4
reg_param:
  desc: null
  value: 0
